on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependências
      run: dotnet restore

    - name: Testes
      run: dotnet test ProjetoPilhaTests/ProjetoPilhaTests.csproj --logger "trx;LogFileName=test_results.trx" --results-directory ./ProjetoPilhaTests/TestResults --verbosity detailed

    - name: Listar Conteúdo do Diretório de Resultados
      run: ls -R ./ProjetoPilhaTests/TestResults
      
    - name: Mostrar Resultados
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./ProjetoPilhaTests/TestResults/test_results.trx

  build:
    runs-on: ubuntu-latest
    needs: testes

    steps:
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependências
      run: dotnet restore
    
    - name: Build
      run: dotnet build
