on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependencias
      run: dotnet restore
    
    - name: Testes
      run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
      
    - name: Mostrar Resultados
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./TestResults/test_results.trx

  build:
    runs-on: ubuntu-latest
    needs: nunit-test-workflow

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependencias
      run: dotnet restore
    
    - name: Build
      run: dotnet build
