on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependências
      run: dotnet restore

    - name: Testes com Cobertura de Código
      run: dotnet test ProjetoPilhaTests/ProjetoPilhaTests.csproj --collect "XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx" --results-directory ./ProjetoPilhaTests/TestResults --verbosity detailed

    - name: Listar Conteúdo do Diretório de Resultados (Cobertura)
      run: ls -R ./ProjetoPilhaTests/TestResults

    - name: Mostrar Resultados
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./ProjetoPilhaTests/TestResults/test_results.trx

    - name: Instalar ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Converter Cobertura para HTML
      run: reportgenerator "-reports:./ProjetoPilhaTests/TestResults/**/*.cobertura.xml" "-targetdir:./ProjetoPilhaTests/TestResults/HTML" -reporttypes:Html

    - name: Upload do Relatório HTML
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: ./ProjetoPilhaTests/TestResults/HTML

  build:
    runs-on: ubuntu-latest
    needs: testes

    steps:
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependências
      run: dotnet restore
    
    - name: Build
      run: dotnet build
